### PR TITLE
fix: update link to docs (fix #603)

### LINKED ISSUE #603: In Session window the link to Capabilities Documentation is broken
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ X ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When we click at Desired Capabilities Documentation link in the Session window it open the broked link:
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

instead 
http://appium.io/docs/en/writing-running-appium/caps/index.html

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ x ] Windows
    - [ ] Linux

### PR DESCRIPTION
**Pull request by jlipps**

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Comment by eglitise** [comment]
Ok, after approving I realised that the app already links to the main documentation through its Help menu. Maybe it's better to instead keep the current text, and just change the link to the [Capabilities page of the new docs](https://appium.io/docs/en/latest/guides/caps/)?
The Help menu links are also a bit outdated though...

**Comment by jlipps** [comment]
good point @eglitise i updated them all

**Comment by jlipps** [comment]
looks like that was unnecessarily duplicated. what do you think now @eglitise

**Review by eglitise — APPROVED** [review]
Looks good now 👍

**Pull request merged**
