### PR TITLE
docs: address possible removal in cloud providers

### PR DESCRIPTION
**Pull request by KazuCocoa**
I think it would be nice to address possible removal in case they are not compatible with our inspector.
https://github.com/appium/appium-inspector/issues/391

### CODE REVIEW

**Review by eglitise — APPROVED** [review]
Makes sense. I'm also thinking of removing Remote TestKit; their website hasn't worked since around June of last year.

**Comment by KazuCocoa** [comment]
> 'm also thinking of removing Remote TestKit; their website hasn't worked since around June of last year.

btw, @eglitise which website?
It looks like https://appkitbox.com/en/category/news/ has some updates thus I assume they keep maintaining the tool. We could ask the original contributor for in an issue to check it, though. In the Japanese website also had some notifications in 2024.

Screenshot 2024-02-15 at 1 19 37 AM

https://appkitbox.com/category/news/

**Comment by eglitise** [comment]
That... is odd, because whenever I try to access this website (including just now), it returns 403 Forbidden. Even tried multiple browsers and locations. Maybe there's some geoblocking going on that wasn't present early last year?

**Comment by KazuCocoa** [comment]
Hm, possibly yes. I saw that GDPR made some websites shut down from EU countries. Could it be related if your access was from around there

**Comment by KazuCocoa** [comment]
hm, then we probably need to address such limitations somehow (maybe in README...?, no idea right now)

**Comment by KazuCocoa** [comment]
I have confirmed with VPN about the 403. Maybe we could do something

**Comment by eglitise** [comment]
If this is indeed due to GDPR, I think the least they could do is change that HTTP 403 to HTTP 451 😅

**Pull request merged**
