### PR TITLE
feat: Support RemoteTestKit into Appium Inspector

### PR DESCRIPTION
**Pull request by nttr-kurisima**

### CODE REVIEW

**Comment by nttr-kurisima** [comment]
Easy CLA approved, so reopen pull request.

**Comment by KazuCocoa** [comment]
Could you add screenshots where this PR modifies in the description?

**Comment by nttr-kurisima** [comment]
Could you please review screenshots below?

RemoteTestKit_screenshot_01
RemoteTestKit_screenshot_02

**Comment by KazuCocoa** [comment]
Do you want to address the service in https://github.com/appium/appium-inspector#supported-cloud-platforms ?

**Comment by nttr-kurisima** [comment]
Platform and Docs addresses for Remote TestKit are below.

Platform: https://appkitbox.com/en/
Docs: https://appkitbox.com/en/support/automation/appium/

**Comment by KazuCocoa** [comment]
Okay, I'm ok if you do not need to address in this readme as same as other vendors

**Pull request merged**
