### PR TITLE
chore: update some cloud provider logos

### PR DESCRIPTION
**Pull request by eglitise**
This PR updates logos for the following cloud providers:
* SauceLabs
* BitBar (not the very latest logo, but I could not find an SVG for it)
* Kobiton
* Perfecto

The only remaining out-of-date logo is Robotic.Mobi, which is handled in #505.

I hope this is okay from a copyright perspective...?

### CODE REVIEW

**Comment by jlipps** [comment]
thanks @eglitise! mind attaching a screenshot of all the new logos for quick verification?

**Comment by jlipps** [comment]
by which i mean a screenshot of the app with all the new logos showing

**Comment by eglitise** [comment]
@jlipps here are screenshots of the provider selection modal, and the server tab bar after selecting the updated ones:
logos-server-selector
logos-server-tabs

**Comment by jlipps** [comment]
awesome, thanks!

**Pull request merged**
