### PR TITLE
fix: update Robotic.Mobi to RobotQA

### PR DESCRIPTION
**Pull request by eglitise**
This PR resubmits the closed PR #505, with a few changes:
* The provider key in `ServerTypes` and `session.server` was not changed, as they were otherwise causing errors
* Added translation key for the token label

### CODE REVIEW

**Comment by donmezburak** [comment]
hi @KazuCocoa . we still need this. last time, this rejected due to cache deletion however couldn't find any solution at that time. we will check this pr and problems asap.

**Review by jlipps — COMMENTED** [review]
code changes look good whenever the content change is approved by robot qa representative

**Comment by donmezburak** [comment]
Hi @jlipps . it looks good for us too. Thanks.

**Comment by eglitise** [comment]
@donmezburak FYI: these changes have been included in Inspector v2023.5.1.

**Pull request merged**
