### PR TITLE
Add LambdaTest cloud provider for real devices

### PR DESCRIPTION
**Pull request by swngarg-lt**

### CODE REVIEW

**Comment by swngarg-lt** [comment]
The LambdaTest link needs to be added under the `Supported cloud platforms` section in readme. Do we need to add that or it'll be added by Appium's team?

**Comment by jlipps** [comment]
@swngarg-lt just go ahead and add it as part of this PR

**Comment by KazuCocoa** [comment]
Sorry, I meant about the README was in macOS's section.

**Review by KazuCocoa — APPROVED** [review]

**Comment by swngarg-lt** [comment]
@KazuCocoa when will these changes start showing in the official appium inspector release?

**Comment by KazuCocoa** [comment]
It seems like this built package has an issue as https://github.com/appium/appium-inspector/releases/tag/v2022.3.2
We can create a pre-release, but maybe we need to investigate the cause before making it a release.
(https://github.com/appium/appium-inspector#installing-on-macos fixes it at least. We'd like to find to apply it in a ci task)

**Comment by jlipps** [comment]
We're currently blocked making releases. Awaiting some help from our open source foundation to get a new app signing certificate (cc @brianwarner)

**Comment by brianwarner** [comment]
Thanks @jlipps. Just confirming this is in progress...

**Comment by vipulkv** [comment]
hi @jlipps @brianwarner - do we have any update on this? we are waiting for a relase from Appium with support of Lambdatest cloud platform.

**Comment by KazuCocoa** [comment]
created a prerelease tag. They still have the known signing issue, but can use by following the README.
https://github.com/appium/appium-inspector/releases/tag/v2022.4.1

**Pull request merged**
